#!/bin/bash

echo "🚀 Analytics Dashboard Deployment Commands"
echo "=========================================="

# Option 1: Netlify CLI
echo ""
echo "📦 NETLIFY DEPLOYMENT:"
echo "----------------------"
echo "# Install Netlify CLI"
echo "npm install -g netlify-cli"
echo ""
echo "# Login to Netlify"
echo "netlify login"
echo ""
echo "# Deploy from analytics-standalone folder"
echo "cd analytics-standalone"
echo "netlify deploy --prod --dir ."
echo ""
echo "# Set custom domain (after deployment)"
echo "netlify domains:add analytics.thecurrentsee.org"

# Option 2: Vercel CLI
echo ""
echo "🔷 VERCEL DEPLOYMENT:"
echo "--------------------"
echo "# Install Vercel CLI"
echo "npm install -g vercel"
echo ""
echo "# Login to Vercel"
echo "vercel login"
echo ""
echo "# Deploy from analytics-standalone folder"
echo "cd analytics-standalone"
echo "vercel --prod"
echo ""
echo "# Add custom domain"
echo "vercel domains add analytics.thecurrentsee.org"

# Option 3: GitHub Pages
echo ""
echo "🐙 GITHUB PAGES DEPLOYMENT:"
echo "---------------------------"
echo "# Create new repository"
echo "git init"
echo "git remote add origin https://github.com/yourusername/current-see-analytics.git"
echo ""
echo "# Add files from analytics-standalone"
echo "cp -r analytics-standalone/* ."
echo "git add ."
echo "git commit -m 'Initial analytics dashboard deployment'"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "# Enable GitHub Pages in repository settings"
echo "# Go to Settings > Pages > Source: Deploy from branch > main"

# Option 4: Simple HTTP Server (for testing)
echo ""
echo "🔍 LOCAL TESTING:"
echo "----------------"
echo "# Test locally before deployment"
echo "cd analytics-standalone"
echo "python3 -m http.server 8080"
echo "# Open: http://localhost:8080"

# Option 5: SCP Upload
echo ""
echo "📤 SCP UPLOAD (if you have a server):"
echo "------------------------------------"
echo "# Upload to your server"
echo "scp -r analytics-standalone/* user@yourserver.com:/var/www/analytics/"

# Option 6: Create ZIP for manual upload
echo ""
echo "📁 CREATE ZIP FOR MANUAL UPLOAD:"
echo "-------------------------------"
echo "cd analytics-standalone"
echo "zip -r analytics-dashboard.zip ."
echo "echo 'Upload analytics-dashboard.zip to your hosting platform'"

echo ""
echo "✅ Commands ready for deployment!"
echo "=========================================="