/**
 * ERA 22.1 — ARMOS API ADAPTER
 * ============================
 * Clean service layer between the TC-S Network and the ArmOS Replicator.
 * The OpenAI frontier orchestrator talks to this adapter — ArmOS-specific
 * HTTP calls are never embedded elsewhere in the application.
 *
 * Authority boundaries (critical):
 *   - Engineering results come from the live ArmOS endpoint (/api/engineer),
 *     where Gemini performs manufacturing inference. They are authoritative.
 *   - The Creation Capsule is a UIM/Replicator protocol artifact derived
 *     mechanically from the authoritative ArmOS engineering result — it is
 *     never generated by the orchestrator LLM. Geometry hashes are computed
 *     (sha256) from the actual returned geometry, never invented.
 *   - Execution runs in SIMULATION mode (execution_mode of the capability).
 *     The lifecycle state machine below is the adapter's authoritative
 *     execution state; the marketplace reflects it directly.
 *   - No API secrets or credentials appear in the descriptor, capsule,
 *     provenance, or any client-visible payload.
 */

const crypto = require('crypto');
const { inferenceRoutingTelemetry, RUNPOD_STATUS } = require('./model-router');

const ARMOS_BASE = 'https://suspicious-pristine-struct.replit.app';

// ── Capability descriptor (UIM network capability, discoverable) ──────────
const CAPABILITY_DESCRIPTOR = {
  capability_id: 'TC-S.REPLICATOR.ARMOS',
  name: 'TC-S Replicator / ArmOS',
  type: 'FABRICATION_ASSEMBLY',
  endpoint: ARMOS_BASE + '/',
  status: 'AVAILABLE',
  execution_mode: 'SIMULATION',
  specialist_inference: {
    provider: 'GOOGLE',
    model_family: 'GEMINI_3',
    roles: ['MANUFACTURING', 'VISION', 'PERCEPTION', 'ASSEMBLY']
  },
  supports: ['ENGINEER', 'CAPSULE', 'FABRICATE', 'PERCEIVE', 'ASSEMBLE', 'INSPECT', 'PROVENANCE'],
  demonstrations: {
    cloud_nine: ARMOS_BASE + '/cloudnine'
  }
};

// ── Era 22.0 node registry (preserved routing behavior) ────────────────────
// RP-0001 compatible table mission → ACCEPTED
// RP-0002 incompatible mission → ROUTE_REQUIRED (ArmOS rejection is final;
//         OpenAI must discover an alternative node, never override)
// RP-0003 large-volume dual-arm → ACCEPTED with dual-arm capability recorded
const NODES = [
  {
    node_id: 'RP-0001',
    name: 'Replicator Node RP-0001',
    class: 'SINGLE_ARM_GENERAL_FABRICATION',
    arms: 1,
    build_envelope_m: { x: 1.5, y: 1.2, z: 1.5 },
    max_part_dimension_m: 1.2,
    capabilities: ['FABRICATE', 'PERCEIVE', 'ASSEMBLE', 'INSPECT'],
    status: 'AVAILABLE'
  },
  {
    node_id: 'RP-0002',
    name: 'Replicator Node RP-0002',
    class: 'PRECISION_MICRO_FABRICATION',
    arms: 1,
    build_envelope_m: { x: 0.25, y: 0.25, z: 0.25 },
    max_part_dimension_m: 0.25,
    capabilities: ['FABRICATE', 'INSPECT'],
    status: 'AVAILABLE'
  },
  {
    node_id: 'RP-0003',
    name: 'Replicator Node RP-0003',
    class: 'LARGE_VOLUME_DUAL_ARM',
    arms: 2,
    dual_arm: true,
    build_envelope_m: { x: 3.0, y: 2.5, z: 3.0 },
    max_part_dimension_m: 2.8,
    capabilities: ['FABRICATE', 'PERCEIVE', 'ASSEMBLE', 'INSPECT', 'DUAL_ARM_COORDINATION'],
    status: 'AVAILABLE'
  }
];

// ── Mission store (in-memory demo store; capped) ──────────────────────────
const MISSIONS = new Map();
const MISSION_CAP = 200;
function rememberMission(m) {
  if (MISSIONS.size >= MISSION_CAP) {
    const oldest = MISSIONS.keys().next().value;
    MISSIONS.delete(oldest);
  }
  MISSIONS.set(m.mission_id, m);
}

function sha256(obj) {
  return crypto.createHash('sha256').update(JSON.stringify(obj)).digest('hex');
}

// ── Adapter operations ─────────────────────────────────────────────────────

async function getCapabilities() {
  // Live availability check against the real ArmOS endpoint.
  let live = false;
  try {
    const r = await fetch(ARMOS_BASE + '/api/health', { signal: AbortSignal.timeout(8000) });
    const j = await r.json().catch(() => ({}));
    live = !!(r.ok && j.ok);
  } catch (e) { live = false; }
  return { capabilities: [{ ...CAPABILITY_DESCRIPTOR, status: live ? 'AVAILABLE' : 'UNREACHABLE' }] };
}

async function getNodes() {
  return { nodes: NODES };
}

/**
 * Authoritative engineering call → live ArmOS /api/engineer (Gemini inference).
 * Fails loud if ArmOS is unreachable — no synthetic engineering results.
 */
async function engineerMission(intent) {
  // ArmOS's upstream gateway can 504 on complex prompts under load — retry a
  // few times before failing loud. Never substitute a synthetic result.
  let r, lastErr;
  for (let attempt = 1; attempt <= 3; attempt++) {
    try {
      r = await fetch(ARMOS_BASE + '/api/engineer', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt: String(intent).slice(0, 500) }),
        signal: AbortSignal.timeout(90000)
      });
      if (r.ok) break;
      const text = await r.text().catch(() => '');
      lastErr = new Error(`ArmOS engineering failed (${r.status}): ${text.slice(0, 200)}`);
      lastErr.status = r.status;
      lastErr.retryable = [408, 425, 429, 500, 502, 503, 504].includes(r.status);
    } catch (e) {
      lastErr = new Error(`ArmOS engineering unreachable: ${e.message}`);
      lastErr.cause = e;
      // Network failures and request timeouts are safe to retry after a
      // cooldown; malformed responses and validation errors are not.
      const networkCode = e.code || (e.cause && e.cause.code);
      lastErr.retryable = e.name === 'AbortError' || e.name === 'TimeoutError' ||
        e.name === 'TypeError' ||
        ['ECONNRESET', 'ECONNREFUSED', 'ETIMEDOUT', 'EAI_AGAIN'].includes(networkCode);
      r = null;
    }
    if (attempt < 3) await new Promise(res => setTimeout(res, 1500 * attempt));
  }
  if (!r || !r.ok) throw lastErr;
  const data = await r.json();
  if (!data.assembly || !Array.isArray(data.assembly.pieces) || data.assembly.pieces.length === 0) {
    throw new Error('ArmOS returned no assembly — engineering result rejected (no fabricated results permitted).');
  }
  return {
    assembly: data.assembly,
    specialist_model: data.model || 'gemini (ArmOS-reported)',
    engineered_at: new Date().toISOString(),
    source: ARMOS_BASE + '/api/engineer'
  };
}

/** Largest bounding dimension of a piece from its primitives (meters). */
function pieceMaxDim(piece) {
  let max = 0;
  for (const p of piece.prims || []) {
    max = Math.max(max, Math.abs(p.a || 0), Math.abs(p.b || 0), Math.abs(p.c || 0));
  }
  return max;
}

function nodeCompatibility(node, assembly) {
  const maxDim = Math.max(...assembly.pieces.map(pieceMaxDim));
  const needsAssembly = assembly.pieces.length > 1;
  if (maxDim > node.max_part_dimension_m) {
    return { verdict: 'ROUTE_REQUIRED', reason: `Largest part dimension ${maxDim.toFixed(2)}m exceeds node envelope ${node.max_part_dimension_m}m.` };
  }
  if (needsAssembly && !node.capabilities.includes('ASSEMBLE')) {
    return { verdict: 'ROUTE_REQUIRED', reason: `Mission requires assembly of ${assembly.pieces.length} parts; node ${node.node_id} has no ASSEMBLE capability.` };
  }
  return { verdict: 'ACCEPTED', reason: 'Node envelope and capabilities are compatible with the mission.' };
}

/**
 * Build the UIM Creation Capsule from the authoritative engineering result and
 * lock it to a node. Model-independent: the capsule is a UIM/Replicator
 * protocol artifact — MODEL → UIM → CREATION CAPSULE → EXECUTION.
 */
async function createCapsule({ mission_id, intent, engineering, node_id }) {
  const node = NODES.find(n => n.node_id === node_id);
  if (!node) throw new Error(`Unknown replicator node: ${node_id}`);
  const compat = nodeCompatibility(node, engineering.assembly);
  if (compat.verdict !== 'ACCEPTED') {
    // ArmOS compatibility rejection is authoritative — orchestrator must
    // discover an alternative node and request a new capsule.
    return { compatibility: compat.verdict, node_id, reason: compat.reason };
  }

  const scrambleSeed = parseInt(sha256({ mission_id, node_id }).slice(0, 8), 16);
  const parts = engineering.assembly.pieces.map((piece, i) => {
    const geometryHash = sha256(piece.prims);
    const maxDim = pieceMaxDim(piece);
    return {
      part_id: `${mission_id}-P${String(i + 1).padStart(2, '0')}`,
      label: piece.label,
      material: 'POLYMER_COMPOSITE_SIM',
      color: piece.color,
      connector: piece.connector,
      dimensions_m: { max: +maxDim.toFixed(3) },
      orientation: piece.mount || { x: 0, y: 0, z: 0 },
      // Sanitized geometry primitives from the authoritative ArmOS engineering
      // result — lets clients render a digital twin of the real part shapes.
      prims: (piece.prims || []).map(p => ({
        kind: p.kind, x: +p.x || 0, y: +p.y || 0, z: +p.z || 0,
        a: +p.a || 0, b: +p.b || 0, c: +p.c || 0
      })),
      geometry_hash: geometryHash,
      grasp_regions: (piece.prims || []).map((p, j) => ({ region_id: `G${j + 1}`, kind: p.kind, offset: { x: p.x, y: p.y, z: p.z } })),
      machine_code_ref: `MC-${geometryHash.slice(0, 12)}`,
      tolerance_mm: 0.5,
      fabrication_estimate_s: Math.round(60 + maxDim * 400),
      material_estimate_kg: +(maxDim * 1.8).toFixed(2),
      energy_estimate_wh: Math.round(20 + maxDim * 150)
    };
  });

  const capsule = {
    capsule_version: 'UIM-CC/22.1',
    mission_id,
    object_name: engineering.assembly.name,
    intent,
    node: { node_id: node.node_id, name: node.name, class: node.class, capabilities: node.capabilities, dual_arm: !!node.dual_arm },
    execution_mode: 'SIMULATION',
    parts,
    assembly_graph: parts.map(p => ({ part_id: p.part_id, attaches_to: p.connector === 'peg' ? 'socket-parent' : 'base', via: p.connector })),
    success_criteria: [
      'All parts fabricated within tolerance',
      'All parts re-identified after scramble via machine perception',
      'Assembly graph satisfied',
      'Inspection pass with zero critical defects'
    ],
    totals: {
      parts: parts.length,
      fabrication_estimate_s: parts.reduce((s, p) => s + p.fabrication_estimate_s, 0),
      material_estimate_kg: +parts.reduce((s, p) => s + p.material_estimate_kg, 0).toFixed(2),
      energy_estimate_wh: parts.reduce((s, p) => s + p.energy_estimate_wh, 0)
    },
    scramble_seed: scrambleSeed,
    inference_routing: inferenceRoutingTelemetry(),
    provenance: {
      engineering_source: engineering.source,
      specialist_model: engineering.specialist_model,
      engineered_at: engineering.engineered_at,
      capsule_hash: null // set below
    }
  };
  capsule.provenance.capsule_hash = sha256({ ...capsule, provenance: null });
  return { compatibility: 'ACCEPTED', capsule };
}

// ── Simulated execution lifecycle ──────────────────────────────────────────
const EXEC_STAGES = ['FABRICATION', 'SCRAMBLE', 'PERCEPTION', 'ASSEMBLY', 'INSPECTION', 'REPLICATION_COMPLETE'];
const STAGE_SECONDS = 4; // per stage, simulation pacing

async function executeMission(mission_id) {
  const m = MISSIONS.get(mission_id);
  if (!m) throw new Error(`Unknown mission: ${mission_id}`);
  if (m.status !== 'WAITING_APPROVAL') throw new Error(`Mission ${mission_id} is ${m.status}, not WAITING_APPROVAL.`);
  m.status = 'EXECUTING';
  m.execution_started_at = Date.now();
  m.timeline.push({ stage: 'APPROVED', at: new Date().toISOString() });
  return { mission_id, status: 'EXECUTING' };
}

function currentStage(m) {
  if (m.status !== 'EXECUTING' && m.status !== 'REPLICATION_COMPLETE') return null;
  const elapsed = (Date.now() - m.execution_started_at) / 1000;
  const idx = Math.min(Math.floor(elapsed / STAGE_SECONDS), EXEC_STAGES.length - 1);
  return { idx, stage: EXEC_STAGES[idx] };
}

async function getMissionStatus(mission_id) {
  const m = MISSIONS.get(mission_id);
  if (!m) throw new Error(`Unknown mission: ${mission_id}`);
  const cur = currentStage(m);
  if (cur) {
    // Append newly-passed stages to the timeline exactly once.
    for (let i = 0; i <= cur.idx; i++) {
      const s = EXEC_STAGES[i];
      if (!m.timeline.find(t => t.stage === s)) m.timeline.push({ stage: s, at: new Date().toISOString() });
    }
    if (cur.stage === 'REPLICATION_COMPLETE' && m.status !== 'REPLICATION_COMPLETE') {
      m.status = 'REPLICATION_COMPLETE';
      m.result = buildResult(m);
    }
  }
  return {
    mission_id,
    status: m.status,
    stage: m.status === 'REPLICATION_COMPLETE' ? 'REPLICATION_COMPLETE' : (cur ? cur.stage : m.status),
    timeline: m.timeline,
    node_id: m.capsule ? m.capsule.node.node_id : null
  };
}

function buildResult(m) {
  const c = m.capsule;
  return {
    mission_id: m.mission_id,
    status: 'REPLICATION_COMPLETE',
    execution_source: 'TC-S_LOCAL_SIMULATION', // NOT live ArmOS machine state:
    // ArmOS exposes engineering only; execution runs in the adapter's declared
    // simulator (capability execution_mode: SIMULATION).
    inspection: {
      source: 'TC-S_LOCAL_SIMULATION',
      verdict: 'PASS',
      parts_inspected: c.parts.length,
      critical_defects: 0,
      tolerances_verified: c.parts.map(p => ({ part_id: p.part_id, tolerance_mm: p.tolerance_mm, within_tolerance: true }))
    },
    perception: {
      source: 'TC-S_LOCAL_SIMULATION',
      scramble_seed: c.scramble_seed,
      parts_rediscovered: c.parts.length,
      identification: c.parts.map(p => ({ part_id: p.part_id, matched_geometry_hash: p.geometry_hash }))
    },
    dual_arm_used: !!c.node.dual_arm,
    provenance: {
      ...c.provenance,
      node_id: c.node.node_id,
      execution_mode: c.execution_mode,
      inference_routing: c.inference_routing,
      open_weight_compute: { provider: 'RunPod', status: RUNPOD_STATUS, requests_routed: 0 },
      completed_at: new Date().toISOString()
    }
  };
}

async function getMissionResult(mission_id) {
  const m = MISSIONS.get(mission_id);
  if (!m) throw new Error(`Unknown mission: ${mission_id}`);
  await getMissionStatus(mission_id); // advance simulated lifecycle first
  if (m.status !== 'REPLICATION_COMPLETE') return { mission_id, status: m.status, result: null };
  return { mission_id, status: m.status, result: m.result };
}

function getMission(mission_id) { return MISSIONS.get(mission_id) || null; }

function createMissionRecord(intent, requestedNodeId = null) {
  // 96-bit random id (unguessable) + separate control token required for
  // state-changing operations (approve/cancel).
  const mission_id = 'TCSM-' + crypto.randomBytes(12).toString('hex').toUpperCase();
  const m = {
    mission_id,
    control_token: crypto.randomBytes(16).toString('hex'),
    intent,
    requested_node_id: requestedNodeId,
    status: 'ORCHESTRATING',
    created_at: new Date().toISOString(),
    timeline: [{ stage: 'MARKETPLACE ORDER', at: new Date().toISOString() }, { stage: 'MISSION INTENT', at: new Date().toISOString() }],
    engineering: null,
    capsule: null,
    routing_events: [],
    orchestrator_summary: null,
    result: null
  };
  rememberMission(m);
  return m;
}

function cancelMission(mission_id) {
  const m = MISSIONS.get(mission_id);
  if (!m) throw new Error(`Unknown mission: ${mission_id}`);
  if (m.status === 'REPLICATION_COMPLETE') throw new Error('Mission already complete.');
  m.status = 'CANCELLED';
  m.timeline.push({ stage: 'CANCELLED', at: new Date().toISOString() });
  return m;
}

module.exports = {
  ARMOS_BASE, CAPABILITY_DESCRIPTOR, NODES,
  getCapabilities, getNodes, engineerMission, createCapsule,
  executeMission, getMissionStatus, getMissionResult,
  getMission, createMissionRecord, cancelMission
};
